# Generated by Django 4.2.7 on 2024-01-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuliana', '0004_alter_kategori_banner_dua_alter_produk_gambar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontak',
            old_name='no_whatsApp',
            new_name='no_whatsup',
        ),
    ]
